alias reload!='. ~/.zshrc'
alias chc='nocorrect chc'
alias chc='touch tmp/cache_classes.txt'
alias rmchc='rm tmp/cache_classes.txt'
alias fs='nocorrect fs'
alias fs='foreman start'
alias mstart='memcached -p21211'
alias rbenv='nocorrect rbenv'
